# Generated by Django 5.2.7 on 2025-11-23 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9Kk\\-]+$', 'El RUT solo puede contener números, guion y K.')])),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(choices=[('medico', 'Médico'), ('administrativo_ingreso', 'Administrativo ingreso'), ('director', 'Director')], max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_salud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
